language: objective-c
osx_image: xcode9
script: 
- xcodebuild test -project DSTaipeiParks.xcodeproj -scheme DSTaipeiParks -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -configuration Debug